name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Lint
        run: |
          changes=$(go fmt .)
          if [[ ! -z $changes  ]]; then
            echo "Linter detected changes in these files"
            echo $changes
            exit 1
          fi

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
