name: Publish image and update deployment
run-name: "Release and deploy for [${{ github.ref_name }}]"

on:
  push:
    tags:
      - "*"

jobs:
  release:
    permissions:
      contents: read
      packages: write
    uses: notarock/tuyauterie/.github/workflows/ImageAutoRelease.yml@main
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rolling-deploy:
    needs: [release]
    uses: notarock/tuyauterie/.github/workflows/UpdateDeploymentVersion.yml@main
    with:
      version: ${{ needs.release.outputs.version }}
      repository: "notarock/gitops"
      deployment-path: "acac/deployment.yaml"
    secrets:
      gitops-token: ${{ secrets.GITOPS_TOKEN }}
